export const billingConstants = {
    BILLING_INTENT_SUCCESS: "BILLING_INTENT_SUCCESS",
    BILLING_INTENT_FAILURE: "BILLING_INTENT_FAILURE",
    SUBSCRIPTION_PURCHASE_SUCCESS: "SUBSCRIPTION_PURCHASE_SUCCESS",
    SUBSCRIPTION_PURCHASE_REQUEST: "SUBSCRIPTION_PURCHASE_REQUEST",
    SUBSCRIPTION_PURCHASE_FAILURE: "SUBSCRIPTION_PURCHASE_FAILURE",
    CREATE_SUBSCRIPTION_SUCCESS: "CREATE_SUBSCRIPTION_SUCCESS",

    CREATE_PAYMENT_METHOD_REQUEST: "CREATE_PAYMENT_METHOD_REQUEST",
    CREATE_PAYMENT_METHOD_SUCCESS: "CREATE_PAYMENT_METHOD_SUCCESS",
    CREATE_PAYMENT_METHOD_FAILURE: "CREATE_PAYMENT_METHOD_FAILURE",

    VALID_COUPON_REQUEST: "VALID_COUPON_REQUEST",
    VALID_COUPON_SUCCESS: "VALID_COUPON_SUCCESS",
    VALID_COUPON_FAILURE: "VALID_COUPON_FAILURE",
    REMOVE_COUPON: "REMOVE_COUPON",
    BILLING_ADDRESS_REQUEST: "BILLING_ADDRESS_REQUEST",
    BILLING_ADDRESS_SUCCESS: "BILLING_ADDRESS_SUCCESS",
    BILLING_ADDRESS_FAILURE: "BILLING_ADDRESS_FAILURE",

    PAYMENT_METHOD_REQUEST: "PAYMENT_METHOD_REQUEST",
    PAYMENT_METHOD_SUCCESS: "PAYMENT_METHOD_SUCCESS",
    PAYMENT_METHOD_FAILURE: "PAYMENT_METHOD_FAILURE",

    APPLIED_COUPON: "APPLIED_COUPON",
};
