export const CONSTANT = {
    LOCAL_STORAGE_LANG_KEY: "RC_LANG_KEY",

    UPDATE_CONNECTIVITY: "UPDATE_CONNECTIVITY",
    SHOW_MENU_DROPDOWN: "SHOW_MENU_DROPDOWN",
    HIDE_MENU_DROPDOWN: "HIDE_MENU_DROPDOWN",
    SHOW_PRICING_DROPDOWN: "SHOW_PRICING_DROPDOWN",
    HIDE_PRICING_DROPDOWN: "HIDE_PRICING_DROPDOWN",
    SHOW_USER_DETAILS_DROPDOWN: "SHOW_USER_DETAILS_DROPDOWN",
    HIDE_USER_DETAILS_DROPDOWN: "HIDE_USER_DETAILS_DROPDOWN",
    EXPAND_MAIN_MENU: "EXPAND_MAIN_MENU",
    COLLAPSE_MAIN_MENU: "COLLAPSE_MAIN_MENU",

    FINISH_FIRST_VISIT: "FINISH_FIRST_VISIT",
    UPDATE_DISPLAY_SETTINGS: "UPDATE_DISPLAY_SETTINGS",
    LANGUAGES: [
        { key: "en", name: "english" },
        { key: "my", name: "Malay" },
        { key: "id", name: "Indonesian" },
        { key: "ch", name: "Chinese" },
    ],
};
export const DEBUG = true;
