export const pricingConstants = {
    GET_PRICING_DETAILS: "USERS_GET_PRICING_DETAILS",
    PRICING_DETAILS_SUCCESS: "USERS_PRICING_DETAILS_SUCCESS",
    PRICING_DETAILS_FAILURE: "USERS_PRICING_DETAILS_FAILURE",
    GET_CAMPAIGN_PRICING_REQUEST: "GET_CAMPAIGN_PRICING_REQUEST",
    GET_CAMPAIGN_PRICING_SUCCESS: "GET_CAMPAIGN_PRICING_SUCCESS",
    GET_CAMPAIGN_PRICING_FAILURE: "GET_CAMPAIGN_PRICING_FAILURE",
};
