export const userConstants = {
    REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
    REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
    REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

    REGISTER_USER_DETAILS: "REGISTER_USER_DETAILS",
    LOGIN_DIALOG_OPEN: "USERS_LOGIN_DIALOG_OPEN",
    FORGOT_DIALOG_OPEN: "USERS_FORGOT_DIALOG_OPEN",
    FORGOT_DIALOG_CLOSE: "USERS_FORGOT_DIALOG_CLOSE",

    DEFAULT_COUNTRY_DIALOG_OPEN: "USERS_DEFAULT_COUNTRY_DIALOG_OPEN",
    DEFAULT_COUNTRY_DIALOG_CLOSE: "USERS_DEFAULT_COUNTRY_DIALOG_CLOSE",
    LOGIN_DIALOG_CLOSE: "USERS_LOGIN_DIALOG_CLOSE",
    LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
    LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
    LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

    RESET_PASSWORD_REQUEST: "USERS_RESET_PASSWORD_REQUEST",
    RESET_PASSWORD_SUCCESS: "USERS_RESET_PASSWORD_SUCCESS",
    RESET_PASSWORD_FAILURE: "USERS_RESET_PASSWORD_FAILURE",
    RESET_PASSWORD_CONFIRM_REQUEST: "USERS_RESET_PASSWORD_CONFIRM_REQUEST",
    RESET_PASSWORD_CONFIRM_SUCCESS: "USERS_RESET_PASSWORD_CONFIRM_SUCCESS",
    RESET_PASSWORD_CONFIRM_FAILURE: "USERS_RESET_PASSWORD_CONFIRM_FAILURE",

    LOGOUT: "USERS_LOGOUT",

    GET_USER: "GET_USER_DETAILS",
    GET_LOGIN_STATUS: "GET_LOGIN_STATUS",
    LOGIN_STATUS_SUCCESS: "LOGIN_STATUS_SUCCESS",
    LOGIN_STATUS_USER_NOT_VERIFIED: "LOGIN_STATUS_USER_NOT_VERIFIED",
    LOGIN_STATUS_FAILURE: "LOGIN_STATUS_FAILURE",

    RESEND_VERIFICATION_EMAIL_REQUEST: "RESEND_VERIFICATION_EMAIL_REQUEST",
    RESEND_VERIFICATION_EMAIL_SUCCESS: "RESEND_VERIFICATION_EMAIL_SUCCESS",
    RESEND_VERIFICATION_EMAIL_FAILURE: "RESEND_VERIFICATION_EMAIL_FAILURE",

    GET_USER_SUBSCRIPTION_REQUEST: "GET_USER_SUBSCRIPTION_REQUEST",
    GET_USER_SUBSCRIPTION_SUCCESS: "GET_USER_SUBSCRIPTION_SUCCESS",
    GET_USER_SUBSCRIPTION_FAILURE: "GET_USER_SUBSCRIPTION_FAILURE",

    DEFAULT_LOCATION_REQUEST: "DEFAULT_LOCATION_REQUEST",
    DEFAULT_LOCATION_SUCCESS: "DEFAULT_LOCATION_SUCCESS",
    DEFAULT_LOCATION_FAILURE: "DEFAULT_LOCATION_FAILURE",
};
